/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#848484",
        "on-secondary-container": "#616363",
        "inverse-on-surface": "#f1f1f1",
        "outline": "#7e7576",
        "primary": "#000000",
        "on-surface": "#1b1b1b",
        "outline-variant": "#cfc4c5",
        "on-background": "#1b1b1b",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-tint": "#5e5e5e",
        "background": "#f9f9f9",
        "primary-container": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#1a1c1c",
        "primary-fixed-dim": "#c6c6c6",
        "surface-container-high": "#e8e8e8",
        "surface-variant": "#e2e2e2",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c6c6c6",
        "on-tertiary-container": "#ff291a",
        "surface-bright": "#f9f9f9",
        "on-error": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "tertiary-container": "#410000",
        "surface-dim": "#dadada",
        "on-surface-variant": "#4c4546",
        "secondary": "#5d5f5f",
        "secondary-container": "#dfe0e0",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e2e2",
        "surface-container-low": "#f3f3f3",
        "surface": "#f9f9f9",
        "tertiary-fixed-dim": "#ffb4a8",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#930100",
        "tertiary-fixed": "#ffdad4",
        "surface-container": "#eeeeee",
        "tertiary": "#000000",
        "on-tertiary-fixed": "#410000",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-fixed-variant": "#454747",
        "secondary-fixed-dim": "#c6c6c7",
        "inverse-surface": "#303030"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      spacing: {
        "margin-mobile": "16px",
        "2xl": "48px",
        "xl": "32px",
        "lg": "24px",
        "unit": "8px",
        "3xl": "64px",
        "gutter": "16px",
        "xs": "4px",
        "md": "16px",
        "sm": "8px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        sans: ["IBM Plex Sans", "system-ui", "sans-serif"],
        mono: ["IBM Plex Mono", "monospace"],
        "display-xl": ["IBM Plex Sans", "sans-serif"],
        "label-caps": ["IBM Plex Mono", "monospace"],
        "body-sm": ["IBM Plex Mono", "monospace"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "title-md": ["IBM Plex Mono", "monospace"],
        "body-lg": ["IBM Plex Mono", "monospace"],
        "headline-lg-mobile": ["IBM Plex Sans", "sans-serif"],
        "display-2xl": ["IBM Plex Sans", "sans-serif"],
        code: ["IBM Plex Mono", "monospace"]
      },
    },
  },
  plugins: [],
}
