import { useCallback, useEffect, useRef, useState } from 'react';
import { Bot, Check, Cpu, Loader2, Play, RefreshCw, Upload, X, Zap } from 'lucide-react';
import { useSimulation } from '../../store/SimulationContext';
import { twinArtifactUrl } from '../../lib/api';
import type { TwinProvenance, TwinStage } from '../../lib/types';

const STAGES: { id: TwinStage; label: string }[] = [
  { id: 'DOWNLOADING', label: 'Downloading source' },
  { id: 'ANALYZING', label: 'Analyzing floor plan' },
  { id: 'GENERATING_GEOMETRY', label: 'Generating 3D geometry' },
  { id: 'GENERATING_TEXTURE', label: 'Generating textures' },
  { id: 'SEMANTIC_PROCESSING', label: 'Mapping semantics' },
  { id: 'EXPORTING', label: 'Exporting GLB' },
  { id: 'COMPLETE', label: 'Complete' },
];

const STAGE_ORDER = STAGES.map((s) => s.id);

function stageIndex(stage: TwinStage): number {
  const i = STAGE_ORDER.indexOf(stage);
  return i < 0 ? -1 : i;
}

function ProvenanceBadge({ provenance }: { provenance: TwinProvenance }) {
  const label = provenance === 'AI' ? 'GPU AI' : provenance === 'PROCEDURAL' ? 'LOCAL' : 'MOCK';
  const cls =
    provenance === 'AI'
      ? 'is-ai'
      : provenance === 'PROCEDURAL'
        ? 'is-procedural'
        : 'is-simulated';
  const hint =
    provenance === 'AI'
      ? 'Generated by a remote GPU AI model'
      : provenance === 'PROCEDURAL'
        ? 'Generated locally from the blueprint'
        : 'Generated from a simulated pipeline (demo data)';
  return (
    <span className={`chip provenance-badge ${cls}`} title={hint}>
      <Bot className="h-3 w-3" />
      {label}
    </span>
  );
}

export default function TwinJobPanel({ onClose }: { onClose: () => void }) {
  const s = useSimulation();
  const [file, setFile] = useState<File | null>(null);
  const [fileError, setFileError] = useState<string | null>(null);
  const [adopting, setAdopting] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    void s.refreshTwinProvider();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const job = s.twinJob;
  const terminal = job && ['COMPLETED', 'FAILED', 'CANCELLED'].includes(job.status);
  const currentStage = job && !terminal ? stageIndex(job.stage) : -1;
  const provenance = job?.provenance ?? s.twinProvider?.provenance ?? null;

  const pickFile = useCallback((f: File | null) => {
    setFile(f);
    setFileError(null);
    if (f && !/image\/(png|jpe?g|webp|bmp)|\.(png|jpe?g|webp|bmp)$/i.test(f.type || f.name)) {
      setFileError('Please choose an image of a floor plan (PNG/JPG/WebP)');
    }
  }, []);

  const build = useCallback(async () => {
    if (!file || s.twinBusy) return;
    // route to the provider the backend reports (colab when its worker is
    // online); undefined lets the backend resolve (env default / auto)
    const provider = s.twinProvider?.online ? s.twinProvider.provider : undefined;
    const id = await s.buildTwin(file, provider);
    if (id) setFile(null);
  }, [file, s]);

  const adopt = useCallback(async () => {
    if (!job?.venue_id || !job.scenario_id) return;
    setAdopting(true);
    try {
      await s.selectScenario(job.scenario_id);
      await s.runSimulation();
    } catch {
      /* errors surface via store */
    } finally {
      setAdopting(false);
    }
  }, [job, s]);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      const f = e.dataTransfer.files?.[0] ?? null;
      pickFile(f);
    },
    [pickFile],
  );

  return (
    <aside className="twin-panel flex h-full w-[340px] flex-col border-l border-od-line bg-od-panel/95 backdrop-blur">
      <div className="flex shrink-0 items-center justify-between border-b border-od-line px-3 py-2">
        <span className="sec-label">Build 3D digital twin</span>
        <button onClick={onClose} className="cursor-pointer text-od-muted transition-colors hover:text-od-ink" aria-label="Close twin panel">
          <X className="h-3.5 w-3.5" />
        </button>
      </div>

      <div className="min-h-0 flex-1 space-y-4 overflow-y-auto px-3 py-3">
        {/* provider status */}
        <div className="flex items-center justify-between gap-2">
          <div className="flex min-w-0 items-center gap-2">
            <span className={`status-dot ${s.twinProvider?.online ? 'is-ok' : 'is-danger'}`} />
            <span className="truncate text-[10px] uppercase tracking-[0.14em] text-od-muted mono-tabular">
              {s.twinProvider?.provider ?? 'unknown'} · {s.twinProvider?.model ?? '—'}
            </span>
          </div>
          {provenance && <ProvenanceBadge provenance={provenance} />}
        </div>

        {!terminal && (
          <>
            {/* upload zone */}
            <div
              onDrop={handleDrop}
              onDragOver={(e) => e.preventDefault()}
              onClick={() => inputRef.current?.click()}
              className="flex cursor-pointer flex-col items-center justify-center gap-2 rounded-md border border-dashed border-od-line bg-od-canvas/60 px-3 py-5 text-center transition-colors hover:border-od-warn"
            >
              <Upload className="h-4 w-4 text-od-muted" />
              <div className="text-[10px] leading-snug text-od-muted">
                {file ? (
                  <span className="font-bold text-od-ink mono-tabular">{file.name}</span>
                ) : (
                  <>
                    Drop a floor plan image
                    <br />
                    or click to choose
                  </>
                )}
              </div>
              <input
                ref={inputRef}
                type="file"
                accept="image/png,image/jpeg,image/webp,image/bmp"
                className="hidden"
                onChange={(e) => pickFile(e.target.files?.[0] ?? null)}
              />
            </div>
            {fileError && <div className="text-[10px] text-od-danger">{fileError}</div>}

            <button className="btn btn-solid w-full" onClick={() => void build()} disabled={!file || s.twinBusy}>
              {s.twinBusy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Cpu className="h-3.5 w-3.5" />}
              BUILD DIGITAL TWIN
            </button>

            <div className="flex items-start gap-2 text-[9px] leading-snug text-od-muted">
              <Zap className="mt-0.5 h-3 w-3 shrink-0" />
              <span>
                The job runs on the {s.twinProvider?.online ? 'connected' : 'offline'} provider and returns a
                GLB model + semantic map that become a runnable CrowdFlow venue.
              </span>
            </div>
          </>
        )}

        {job && !terminal && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-[9px] uppercase tracking-[0.16em] text-od-muted mono-tabular">{job.id}</span>
              <span className={`status-dot ${s.twinWsConnected ? 'is-scan' : 'is-warn'}`} title={s.twinWsConnected ? 'live' : 'connecting'} />
            </div>
            <div className="h-1.5 w-full overflow-hidden rounded-full bg-od-line">
              <div className="h-full rounded-full bg-od-warn transition-all duration-300" style={{ width: `${job.progress}%` }} />
            </div>
            <div className="text-[10px] font-bold text-od-ink mono-tabular">{job.progress}% · {job.stage.replace(/_/g, ' ')}</div>
            <ol className="space-y-1">
              {STAGES.map((st) => {
                const idx = stageIndex(st.id);
                const state = currentStage > idx ? 'done' : currentStage === idx ? 'active' : 'todo';
                return (
                  <li key={st.id} className="flex items-center gap-2 text-[10px]">
                    <span className={`h-1.5 w-1.5 rounded-full ${state === 'done' ? 'bg-od-ok' : state === 'active' ? 'animate-pulse bg-od-warn' : 'bg-od-line'}`} />
                    <span className={state === 'done' ? 'text-od-ok line-through opacity-70' : state === 'active' ? 'font-bold text-od-ink' : 'text-od-muted'}>
                      {st.label}
                    </span>
                  </li>
                );
              })}
            </ol>
            {job.status === 'RUNNING' && job.stage === 'GENERATING_GEOMETRY' && (
              <div className="flex items-center gap-2 text-[9px] text-od-muted">
                <Loader2 className="h-3 w-3 animate-spin" />
                {s.twinProvider?.provenance === 'AI'
                  ? 'Waiting for the GPU worker…'
                  : 'Reconstructing locally…'}
              </div>
            )}
            <button className="btn btn-ghost w-full" onClick={() => void s.cancelTwin()}>CANCEL</button>
          </div>
        )}

        {job && terminal && (
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              {job.status === 'COMPLETED' ? (
                <>
                  <Check className="h-3.5 w-3.5 text-od-ok" />
                  <span className="text-[11px] font-bold uppercase tracking-[0.14em] text-od-ok">Twin ready</span>
                </>
              ) : job.status === 'CANCELLED' ? (
                <span className="text-[11px] font-bold uppercase tracking-[0.14em] text-od-muted">Cancelled</span>
              ) : (
                <span className="text-[11px] font-bold uppercase tracking-[0.14em] text-od-danger">Failed</span>
              )}
            </div>

            <div className="space-y-1 text-[10px] text-od-muted mono-tabular">
              <div className="flex justify-between gap-2"><span>Job</span><span className="text-od-ink">{job.id}</span></div>
              <div className="flex justify-between gap-2"><span>Provider</span><span className="text-od-ink">{job.provider} / {job.model}</span></div>
              <div className="flex justify-between gap-2"><span>Provenance</span><ProvenanceBadge provenance={job.provenance} /></div>
              {job.venue_id && <div className="flex justify-between gap-2"><span>Venue</span><span className="text-od-ink">{job.venue_id}</span></div>}
            </div>

            {job.status === 'COMPLETED' && job.venue_id && (
              <button className="btn btn-solid w-full" onClick={() => void adopt()} disabled={adopting}>
                {adopting ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Play className="h-3.5 w-3.5" />}
                USE TWIN · RUN EVENT
              </button>
            )}

            {job.artifacts.length > 0 && (
              <div className="space-y-1">
                <span className="sec-label">Artifacts</span>
                {job.artifacts.map((a) => (
                  <a
                    key={a.name}
                    href={twinArtifactUrl(job.id, a.name)}
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center justify-between rounded border border-od-line px-2 py-1.5 text-[10px] mono-tabular text-od-muted transition-colors hover:border-od-warn hover:text-od-ink"
                  >
                    <span>{a.name}</span>
                    <span className="text-[9px]">{(a.size_bytes / 1024).toFixed(1)} KB</span>
                  </a>
                ))}
              </div>
            )}

            {job.status === 'FAILED' && (
              <button className="btn btn-ghost w-full" onClick={() => void s.retryTwin()}>
                <RefreshCw className="h-3 w-3" /> RETRY
              </button>
            )}

            {job.status === 'COMPLETED' && (
              <button className="btn btn-ghost w-full" onClick={() => void s.clearTwin()}>NEW BUILD</button>
            )}
          </div>
        )}
      </div>
    </aside>
  );
}